[package]
name = "fetch-license-list-from-spdx"
version = "0.1.0"
authors = []
publish = false

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1"
error-chain = "0.12"
